dolphin_webapp/dolphin_note/urls.py
from django.conf.urls import url, include

from dolphin_note.views import (
    common,
    label,
    project,
    note,
    notification,
    schedule
)

app_name = "dolphin_note"

sheduler_patterns = [
    url(r'(?P<scheduler_id>[0-9]+)/delete/$', schedule.delete_scheduler, name='delete_schedule'),
    url(r'^$', schedule.show_schedules, name='show_schedules')
]

#####

exact_notification_patterns = [
    url(r'^remove_notification/$', notification.remove_notification, name='delete_notification'),
]

notifications_patterns = [
    url(r'^(?P<notification_id>[0-9]+)/', include(exact_notification_patterns)),
    url(r'today/$', notification.check_today_notifications, name='check_today_notifications'),
    url(r'week/$', notification.check_week_notifications, name='check_week_notifications'),
    url(r'custom/$', notification.check_custom_period_notifications, name='check_custom_period_notifications'),
]


#####

exact_label_patterns = [
    url(r'^remove/$', label.remove_label, name='delete_label'),
    url(r'(?P<note_id>[0-9]+)/delete_label/$', label.remove_note_label, name='deassign_label'),
    url(r'(?P<note_id>[0-9]+)/delete_label/$', label.remove_note_label, name='deassign_from'),
    url(r'show_notes/$', label.show_label_notes, name='show_label_notes')
]

label_patterns = [
    url(r'^(?P<label_id>[0-9]+)/', include(exact_label_patterns)),
    url(r'^create/$', label.add_label, name='add_label'),
]


#####

exact_note_patterns = [
    url(r'^assign/$', note.assign_user_to_note, name='assign_to_note'),
    url(r'^deassign/(?P<username>.+)/$', note.deassign_user_from_note, name='deassign_from_note'),
    url(r'^update/$', note.update_note, name='update_note'),
    url(r'^update_archive_status/$', note.change_archive_status, name='update_archive_status'),
    url(r'^remove/$', note.remove_note, name='delete_note'),
    url(r'^show/', note.show_details, name='show_note'),
    url(r'create/', note.add_note, name='add_subnote'),
    url(r'add_notification/$', notification.add_notification, name='add_notification'),
    url(r'add_label/$', label.assign_label_to_note, name='assign_label'),
    url(r'create_subnote_scheduler/$', schedule.add_recurring_note_creation, name='create_subnote_scheduler')
]

notes_patterns = [
    url(r'^(?P<note_id>[0-9]+)/', include(exact_note_patterns)),
]


#####

exact_project_patterns = [
    url(r'^assign/$', project.assign_user_to_project, name='assign_to_project'),
    url(r'^deassign/(?P<username>.+)/$', project.deassign_user_from_project, name='deassign_from_project'),
    url(r'^update/$', project.update_project, name='update_project'),
    url(r'^remove/$', project.delete_project, name='delete_project'),
    url(r'^show_notes/', project.project_notes_tree, name='show_notes'),
    url(r'^create/$', note.add_note, name='create_note'),
    url(r'^create_scheduler/$', schedule.add_recurring_note_creation, name='create_sheduler'),
]

projects_patterns = [
    url(r'^(?P<project_id>[0-9]+)/', include(exact_project_patterns)),
    url(r'^create/$', project.create_project, name='create_project'),
]


search_patterns = [
    url(r'^(?P<search_value>[a-zA-Z0-9]+)/', common.search),
]


#####

oauth_patterns = [
    url(r'^login/$', common.login, name='login'),
    url(r'^logout/$', common.logout, name='logout'),
    url(r'^signup/$', common.signup, name='signup'),
]

urlpatterns = [
    url(r'^$', common.home, name='home'),
    url(r'^', include(oauth_patterns)),
    url(r'^project/', include(projects_patterns)),
    url(r'^projects_list/', project.project_list, name='projects_list'),
    url(r'^label/', include(label_patterns)),
    url(r'^labels_list/$', label.labels_list, name='labels_list'),
    url(r'^note/', include(notes_patterns)),
    url(r'^search/', include(search_patterns)),
    url(r'^assigned_notes/', note.show_assigned_notes, name='show_assigned_notes'),
    url(r'^notifications/', include(notifications_patterns)),
    url(r'^scheduler/', include(sheduler_patterns)),
]

dolphin_webapp/dolphin_webapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path


app_name = "dolphin_webapp"


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('dolphin_note.urls')),
]

urlpatterns += staticfiles_urlpatterns()

dolphin_webapp/dolphin_note/views/forms/constants.py
from dolphin_note_library.models.note import NotePriority

PRIORITY_CHOICES = (
    (NotePriority.LOW.value, 'Low'),
    (NotePriority.NORMAL.value, 'Normal'),
    (NotePriority.IMPORTANT.value, 'Important'),
    (NotePriority.HIGH.value, 'High'),
)

dolphin_webapp/dolphin_note/views/common.py
from dateutil.relativedelta import relativedelta
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import (
    render,
    redirect,
)
from django.template.loader import render_to_string

import dolphin_note_library.commands.user as user_commands
from dolphin_note.views.forms.ouath import (
    SignUpForm,
    LoginForm,
)
from dolphin_note.views.utils.decorators import provide_session
from dolphin_note.views.utils.relativedelta_constants import WEEK
from dolphin_note_library.commands.label import find_labels_by_name_like
from dolphin_note_library.commands.note import find_notes_by_name_like
from dolphin_note_library.commands.notification import check_notifications
from dolphin_note_library.commands.project import find_projects_by_name_like


@provide_session
def signup(request, session):
    args = {'form': SignUpForm()}
    if request.POST:
        user_form = SignUpForm(request.POST)
        print(user_form)
        if user_form.is_valid():
            user_form.save()
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password1']
            user = auth.authenticate(username=username, password=password)
            alchemy_user = user_commands.add_user_with_id(session, user.id, user.username)
            auth.login(request, user)
            return redirect('/')

        args['form'] = user_form
        args['user'] = request.user

    return render(request, 'oauth/sign_up.html', args)


def login(request):
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return redirect('/')

            login_error = 'Incorrect password.'
            args = {
                'form': form,
                'login_error': login_error
            }

            return render(request, 'oauth/login.html', args)

        login_error = 'Form is invalid.'
        args = {
            'form': form,
            'login_error': login_error
        }
        return render(request, 'oauth/login.html', args)

    form = LoginForm()
    return render(request, 'oauth/login.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('/')


@provide_session
def home(request, session):
    if request.user.is_authenticated:
        username = request.user.username
        due_date_notes, notifications = check_notifications(
            session,
            request.user.id,
            WEEK
        )
        notifications_list = render_to_string(
            'notifications_list.html',
            {
                'period': WEEK,
                'due_date_notes': due_date_notes,
                'notifications': notifications
            }
        )
        return render(
            request,
            'index.html',
            {
                'notifications_list': notifications_list,
                'username': username

            }
        )
    return render(request, 'oauth/not_auth.html')


@login_required
@provide_session
def search(request, session, search_value):

    projects = find_projects_by_name_like(session, request.user.id, text=search_value)
    notes = find_notes_by_name_like(session, request.user.id, text=search_value)
    labels = find_labels_by_name_like(session, request.user.id, text=search_value)

    return render(
        request,
        'search_list.html',
        {
            'projects': projects,
            'notes': notes,
            'labels': labels
        }
    )

dolphin_webapp/dolphin_note/views/label.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse

import dolphin_note_library.commands.label as label_commands
from dolphin_note.views.forms.label import (
    AddLabelForm,
    AssignLabelFormChoices,
)
from dolphin_note.views.utils.decorators import provide_session
from dolphin_note.views.utils.relativedelta_constants import WEEK
from dolphin_note.views.utils.template_rendering import (
    get_note_info_render,
    get_form_render,
    get_notifications_list)


@login_required
@provide_session
def labels_list(request, session):
    labels = label_commands.get_user_labels(session, request.user.id)
    if request.method == 'GET':
        return render(
            request,
            'labels_list.html',
            {
                'labels': labels
            }
        )


@login_required
@provide_session
def add_label(request, session):
    if request.method == 'POST':
        form = AddLabelForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            label = label_commands.add_label(session, request.user.id, name)
            return get_notifications_list(request, session, WEEK)
    else:
        form = AddLabelForm()
        return get_form_render(session, request, form, reverse('dolphin_note:add_label'))


@login_required
@provide_session
def assign_label_to_note(request, session, note_id):
    if request.method == 'POST':
        form = AssignLabelFormChoices(
            session,
            request.user.id,
            note_id,
            request.POST
        )
        if form.is_valid():
            name = form.cleaned_data['name']
            label = label_commands.get_label_by_name(session, request.user.id, name)
            note_label = label_commands.assign_label_to_note(
                session,
                request.user.id,
                note_id,
                label.id
            )
            return get_note_info_render(session, request, note_id)
    else:
        form = AssignLabelFormChoices(session, request.user.id, note_id)
        return get_form_render(
            session,
            request,
            form,
            reverse(
                'dolphin_note:assign_label',
                kwargs={
                    'note_id': note_id
                }
            )
        )


@login_required
@provide_session
def remove_note_label(request, session, note_id, label_id):
    if request.method == 'POST':
        result = label_commands.remove_note_label(
            session,
            request.user.id,
            note_id,
            label_id
        )
        return get_note_info_render(session, request, note_id)


@login_required
@provide_session
def remove_label(request, session, label_id):
    if request.method == 'POST':
        label = label_commands.get_label_by_id(session, request, label_id)
        session.delete(label)
        session.commit()
        labels = label_commands.get_user_labels(session, request.user.id)
        return render(
            request,
            'labels_list.html',
            {
                'labels': labels
            }
        )


@login_required
@provide_session
def show_label_notes(request, session, label_id):
    if request.method == 'GET':
        label = label_commands.get_label_by_id(session, request, label_id)
        return render(request, 'label_notes_list.html', {'label': label})

dolphin_webapp/dolphin_note/views/notification.py
from datetime import datetime, date

from dateutil.relativedelta import relativedelta
from django.urls import reverse

import dolphin_note_library.commands.notification as notification_commands
from dolphin_note.views.forms.notification import (
    AddNotificationForm,
    NotificationCheckPeriodForm,
)
from dolphin_note.views.utils.decorators import provide_session
from dolphin_note.views.utils.relativedelta_constants import (
    WEEK,
    DAY,
)
from dolphin_note.views.utils.template_rendering import (
    get_form_render,
    get_note_info_render,
)
from dolphin_note.views.utils.template_rendering import get_notifications_list


@provide_session
def add_notification(request, session, note_id):
    if request.method == 'POST':
        form = AddNotificationForm(request.POST)
        if form.is_valid():
            delta = form.cleaned_data['delta']
            if not delta:
                delta = relativedelta()
            notification_date = form.cleaned_data['notification_date']
            notification_date = datetime(notification_date.year,
                                         notification_date.month,
                                         notification_date.day)
            notification = notification_commands.add_time_notification(session, request.user.id,
                                                                       note_id, notification_date, delta)
            return get_note_info_render(session, request, note_id)

    form = AddNotificationForm(
        initial={
            'notification_date': date.today()
        }
    )
    return get_form_render(
        session,
        request,
        form,
        reverse(
            'dolphin_note:add_notification',
            kwargs={
                'note_id': note_id
            }
        )
    )


@provide_session
def remove_notification(request, session, notification_id):
    if request.method == 'POST':
        note_id = notification_commands.get_notification_by_id(
            session,
            request.user.id,
            notification_id
        ).note_id
        result = notification_commands.delete_time_notification(
            session,
            request.user.id,
            notification_id
        )
        if result:
            return get_note_info_render(session, request, note_id)


@provide_session
def check_today_notifications(request, session):
    if request.method == 'GET':
        return get_notifications_list(
            request,
            session,
            DAY
        )


@provide_session
def check_week_notifications(request, session):
    if request.method == 'GET':
        return get_notifications_list(
            request,
            session,
            WEEK
        )


@provide_session
def check_custom_period_notifications(request, session):
    if request.method == 'GET':
        form = NotificationCheckPeriodForm()
        return get_form_render(
            session,
            request,
            form,
            reverse('dolphin_note:check_custom_period_notifications')
        )
    else:
        form = NotificationCheckPeriodForm(request.POST)
        if form.is_valid():
            delta = form.cleaned_data['delta']
            return get_notifications_list(request, session, delta)

dolphin_webapp/dolphin_note/views/schedule.py
from datetime import date

from django.shortcuts import render
from django.urls import reverse

import dolphin_note_library.commands.schedule as sheduler_commands
from dolphin_note.views.forms.schedule import AddScheduleForm
from dolphin_note.views.utils.decorators import provide_session
from dolphin_note.views.utils.template_rendering import get_form_render


def _show_schedulers(request, session):
    schedulers = sheduler_commands.get_all_user_schedules(session, request.user.id)
    sheduler_commands.create_user_notes_from_schedules(session, request.user.id)
    return render(
        request,
        'schedulers_list.html',
        {
            'schedules': schedulers
        }
    )


@provide_session
def show_schedules(request, session):
    if request.method == 'GET':
        return _show_schedulers(request, session)


@provide_session
def delete_scheduler(request, session, scheduler_id):
    if request.method == 'POST':
        result = sheduler_commands.remove_schedule(session, request.user.id, scheduler_id)
        if result:
            return _show_schedulers(request, session)


@provide_session
def add_recurring_note_creation(request, session, note_id=None):
    if request.method == 'POST':
        form = AddScheduleForm(request.POST)
        print(form.errors)
        if form.is_valid():
            delta = form.cleaned_data['delta']
            start_date = form.cleaned_data['start_date'].replace(tzinfo=None)
            end_date = form.cleaned_data['end_date']
            if end_date:
                end_date.replace(tzinfo=None)
            schedule = sheduler_commands.add_schedule(
                session,
                request.user.id,
                delta=delta,
                start_date=start_date,
                end_date=end_date,
                note_id=note_id
            )
            return _show_schedulers(request, session)

    form = AddScheduleForm(initial={
        'start_date': date.today(),
        'due_date': date.today()
    })
    return get_form_render(
        session,
        request,
        form,
        reverse(
            'dolphin_note:create_subnote_scheduler',
            kwargs={
                'note_id': note_id
            }
        )
    )

dolphin_webapp/dolphin_note/templates/label_notes_list.html
<div class="conent">
{% if label.note_labels %}
<table class="table">
<thead>
<th>
    Name
</th>
<th>
    Project
</th>
<th>
</th>
</thead>
<tbody>
{% for note_label in label.note_labels %}
<tr>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_note' note_id=note_label.note.id %}" >
      {{note_label.note.name}}
    </a>
  </td>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_notes' project_id=note_label.note.project.id %}" >
      {{ note_label.note.project.name }}
    </a>
  </td>
<td>
  <a class="post-action" href="{% url 'dolphin_note:deassign_label' note_id=note_label.note_id label_id=note_label.label_id %}">
    <i class="material-icons">
    label_off
    </i>
  </a>
</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% else %}
<div class="alert alert-warning alert-dismissible fade show conent" role="alert">
    No notes have <b>{{label.name}}</b> label
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

dolphin_webapp/dolphin_note/templates/labels_list.html
<div id="labels">
<table class="table table-hover">
<tbody>
{% for label in labels %}
  <tr>
    <td>
      <a href="{% url 'dolphin_note:show_label_notes' label_id=label.id %}"
         class="get-action">
        {{ label.name }}
      </a>
    </td>
    <td align="right">
      {% csrf_token %}
      <a href="{% url 'dolphin_note:delete_label' label_id=label.id %}"
         class="left-pannel-post update-labels-list">
        <i class="fa fa-times"></i>
      </a>
    </td>
  </tr>
{% endfor %}
</tbody>
</table>
</div>

dolphin_webapp/dolphin_note/templates/note_info.html
{% csrf_token %}
{% load humanize %}
{% load timedelta %}
<div align="center" class="conent">
<a class="get-action"
   href="{% url 'dolphin_note:assign_to_note' note_id=note.id %}"
   role="button">
  <i class="fa fa-user-plus"></i>
  Add Collaborator
</a>
<a class="get-action"
   href="{% url 'dolphin_note:update_note' note_id=note.id %}"
   role="button">
  <i class="fa fa-edit"></i>
  Update Note
</a>
<a class="get-action"
   href="{% url 'dolphin_note:add_subnote' note_id=note.id %}"
   role="button">
  <i class="fa fa-plus"></i>
  Add Subnote
</a>
</div>

{% if note.collaborators %}
<div class="conent"></div>
Assigned users:
{%with collaborators=note.collaborators template_name="assigned_to_note_list.html" %}
  {% include template_name %}
{%endwith%}
{% endif %}


<table class="table conent table-hover">
<tbody>
  <tr>
    <td>Name:</td>
    <td>{{ note.name }}</td>
  </tr>
  <tr>
    <td>Project:</td>
      <td>
     <a class="get-action" href="{% url 'dolphin_note:show_notes' project_id=note.project.id%}">
       {{ note.project.name }}
     </a>
  </td>
  </tr>
  <tr>
    <td>Deadline date:</td>
    <td>{{ note.due_date }}</td>
  </tr>
  <tr>
    <td>Priority:</td>
    <td>{{ note.priority.value }}</td>
  </tr>
  <tr>
    <td>Author:</td>
    <td>{{ note.creator.username }}(ID: {{ note.creator.id }})</td>
  </tr>
  <tr>
    <td>Archive:</td>
    <td>{{ note.is_archived }}</td>
  </tr>
  <tr>
    <td>Creation date:</td>
    <td>{{ note.creation_date }}</td>
  </tr>
  <tr>
    <td>Last updated:</td>
    <td>{{ note.updation_date }}</td>
  </tr>
</tbody>
</table>


{% if note_labels %}
<div id="noteLabels" class="conent">
Labels:
<table class="table">
<tbody>
<tr>
  <td>
    {% for note_label in note_labels %}
    <div class="badge badge-info">
    {{note_label.label.name}}
    <a href="{% url 'dolphin_note:deassign_label' label_id=note_label.label_id note_id=note_label.note_id %}"
       class="post-action">
      <i class="fa fa-times"></i>
    </a>
    </div>
   {% endfor %}
  </td>
</tr>
</tbody>
</table>
{% endif %}
<a class="get-action"
   href="{% url 'dolphin_note:assign_label' note_id=note.id %}"
   role="button">
    <i class="fa fa-tag fa-rotate-90"></i>
      Assign Label
</a>
</div>

<div id="notificationsList" class="conent">
{% if notifications %}
Notifications:
<table class="table">
<tbody>
<tr>
  <td>
    {% for notification in notifications %}
    <div class="badge badge-info">
    <i class="mdi mdi-alarm"></i>
    {{ notification.date|naturalday }} |
    <i class="fa fa-repeat"></i>
    {{ notification.delta|timedelta }}
    <a href="{% url 'dolphin_note:delete_notification' notification_id=notification.id %}"
       class="post-action">
      <i class="fa fa-times"></i>
    </a>
    </div>
   {% endfor %}
  </td>
</tr>
</tbody>
</table>
{% endif %}
<a class="get-action"
   href="{% url 'dolphin_note:add_notification' note_id=note.id %}"
   role="button">
    <i class="fa fa-bell"></i>
    Add Notification
</a>
</div>


<div id="noteSchedulesList" class="conent">
{% if notifications %}
Schedules:
<table class="table">
<tbody>
<tr>
  <td>
    {% for schedule in note.schedulers %}
    <div class="badge badge-info">
    <i class="fa fa-calendar"></i>
    {{ schedule.start_date|naturalday }} - {{ schedule.end_date|naturalday }} |
    <i class="fa fa-repeat"></i>
    {{ schedule.delta|timedelta }}
    <a href=""
       class="post-action">
      <i class="fa fa-times"></i>
    </a>
    </div>
   {% endfor %}
  </td>
</tr>
</tbody>
</table>
{% endif %}
<a class="get-action"
   href="{% url 'dolphin_note:create_subnote_scheduler' note_id=note.id %}"
   role="button">
  <i class="fa fa-calendar-plus-o" aria-hidden="true"></i>
  Add Schedule
</a>
</div>

{% csrf_token %}

dolphin_webapp/dolphin_note/templates/note_tree.html
<li class="note-item">
<div class="note-item-content dolphin-table tree-cell-content">
  <a {% if node.is_archived %} style="text-decoration: line-through;" {% endif %}
    href="{% url 'dolphin_note:update_archive_status' note_id=node.id %}"
    class="strike-out"
    title="Send note to archive">
      {{node.name}}
  </a>
  <div class="tree-cell-item">
  </div>
  <div class="tree-cell-item" align="right">
    <div class="hideble inline">
        <a class="get-action"
           href="{% url 'dolphin_note:add_subnote' note_id=node.id %}"
           title="Add subnote">
          <i class="fa fa-plus" aria-hidden="true"></i>
        </a>
        <a class="get-action"
           href="{% url 'dolphin_note:show_note' note_id=node.id %}"
           title="Note info">
          <i class="fa fa-info-circle" aria-hidden="true"></i>
        </a>
        <a class="get-action"
           href="{% url 'dolphin_note:create_subnote_scheduler' note_id=node.id %}"
           title="Add repeatition">
          <i class="mdi mdi-calendar-clock"></i>
        </a>
        <a class="post-action"
           href="{% url 'dolphin_note:delete_note' note_id=node.id %}"
           title="Delete note">
          <i class="fa fa-times" aria-hidden="true"></i>
        </a>
    </div>
    <div class="inline" style="padding-right: 6px">
       <i class="fa fa-circle fa-spin" aria-hidden="true" style="color: {{ node.get_priority_color }}"></i>
    </div>
  </div>
</div>

{%if node.has_childs %}
<ul>
    {%for ch in node.subnotes %}
      {%with node=ch template_name="note_tree.html" %}
           {% include template_name %}
      {%endwith%}
    {%endfor%}
 </ul>
{%endif%}
</li>

dolphin_webapp/dolphin_note/templates/notifications_list.html
{% load humanize %}
{% load timedelta %}
<div class="alert alert-light alert-dismissible fade show conent" role="alert">
  This is your activity for {{ period|timedelta }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="conent" id="dueDateList">
{% if due_date_notes %}
Note Deadlines:
<table class="table">
<thead>
<th>
    Name
</th>
<th>
    Project
</th>
<th>
    Deadline
</th>
<th>
</th>
</thead>
<tbody>
{% for due_date_note in due_date_notes %}
<tr>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_note' note_id=due_date_note.id %}" >
      {{due_date_note.name}}
    </a>
  </td>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_notes' project_id=due_date_note.project.id %}" >
      {{ due_date_note.project.name }}
    </a>
  </td>
  <td>
    {{ due_date_note.due_date|naturalday }}
  </td>
<td>
  <a class="post-action" href="{% url 'dolphin_note:delete_note' note_id=due_date_note.id %}">
    <i class="fa fa-times"></i>
  </a>
</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}
<div id="notificationsList">
{% if notifications %}
Notifications:
<table class="table">
<thead>
<th>
    Note
</th>
<th>
    Project
</th>
<th>
    Date
</th>
<th>
    Repeats
</th>
<th>
</th>
</thead>
<tbody>
{% for notification in notifications %}
<tr>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_note' note_id=notification.note.id %}" >
      {{notification.note.name}}
    </a>
  </td>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_notes' project_id=notification.note.project.id %}" >
      {{ notification.note.project.name }}
    </a>
  </td>
  <td>
    {{notification.date}}
  </td>
  <td>
    {{notification.delta|timedelta}}
  </td>
  <td>
    <a href="{% url 'dolphin_note:delete_notification' notification_id=notification.id %}"
       class="post-action">
      <i class="fa fa-times"></i>
    </a>
  </td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}
</div>

dolphin_webapp/dolphin_note/templates/search_list.html
{% load humanize %}
{% if projects %}
<div id="recentProjects" class="conent">
<table class="table table-hover">
<thead>
  <tr><p>Projects:</p></tr>
  <tr></tr>
  <tr></tr>
</thead>
<tbody>
{% for project in projects %}
<tr>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_notes' project_id=project.id%}">{{ project.name }}</a>
  </td>
<td align="right">
  <a href="{% url 'dolphin_note:update_project' project_id=project.id %}" class="get-action">
    <i class="fa fa-edit"></i>
  </a>
  <a class="left-pannel-post update-project-list" href="{% url 'dolphin_note:delete_project' project.id %}">
    <i class="fa fa-times"></i>
  </a>
</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}
{% if notes %}
<div class="conent">
Notes:
<table class="table">
<tbody>
{% for note in notes %}
<tr>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_note' note_id=note.id %}" >
      {{note.name}}
    </a>
  </td>
  <td>
    <a class="get-action" href="{% url 'dolphin_note:show_notes' project_id=note.project.id %}" >
      {{ note.project.name }}
    </a>
  </td>
  <td>
    {{ note.due_date|naturalday }}
  </td>
  <td>
    <a class="post-action" href="{% url 'dolphin_note:delete_note' note_id=note.id %}">
      <i class="fa fa-times"></i>
    </a>
  </td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}
{% if labels %}
<div id="labels">
<table class="table table-hover">
<thead>
  <tr><p>Labels:</p></tr>
  <tr></tr>
  <tr></tr>
</thead>
<tbody>
{% for label in labels %}
  <tr>
    <td>
        {{ label.name }}
    </td>
    <td align="right">
      {% csrf_token %}
      <a href="{% url 'dolphin_note:delete_label' label_id=label.id %}"
         class="left-pannel-post ">
        <i class="fa fa-times"></i>
      </a>
    </td>
  </tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}